projeto:
  nome: "Meu Portfólio"
  autor: "Argenis López"
  descricao: "Portfólio pessoal para exibir projetos e estudos."
  versao: "1.0.0"
  ano: 2025

links:
  github: "https://github.com/argenis972"
  linkedin: "https://www.linkedin.com/in/argenis-lopez-649701304"
  email: "argenislopez28708256@gmail.com"
